/* Sends only chart aggregates after an explicit user action. Never persists API keys. */
(function(){
const q=id=>document.getElementById(id);
function payload(){return {period:state.period,totalReports:state.rows.length,trendReports:state.trendRows.length,invalidDates:state.errors,otherYearDates:state.outside,charts:state.charts.filter(c=>c.selected).map(c=>({id:c.id,title:c.title,subtitle:c.subtitle,type:c.type,labels:c.type==='cross'?c.series:undefined,data:c.data}))}}
function prompt(){return `شما تحلیلگر ایمنی بیمار هستید. بر اساس آمار تجمیعی زیر، فقط به زبان فارسی و فقط JSON معتبر بدون markdown برگردانید. برای هر id نمودار دقیقاً یک کلید در charts بسازید، شامل observation (حداکثر ۲۰۰ نویسه؛ فقط داده و مخرج درست)، question (حداکثر ۱۶۰ نویسه؛ پرسش برای بررسی)، action (حداکثر ۱۶۰ نویسه؛ اقدام اجرایی برای بررسی). در conclusion جمع‌بندی جامع حداکثر ۷۵۰ نویسه بنویسید؛ اولویت‌ها، کیفیت داده، و اقدام پیگیری را مشخص کنید. درصد، روند علّی، نرخ خطر، علت قطعی و مقایسهٔ ریسک را بدون مخرج معتبر ادعا نکنید. بخش ۲ را «بخش مرتبط» بخوانید، نه محل قطعی وقوع. علل ثبت شده برداشت گزارش‌دهنده‌اند. در نمودار cross فقط پنج واحد برتر هستند. دسته‌های نقص داده همپوشانی دارند. همهٔ رکوردها در نمودارهای دسته‌ای‌اند ولی روند فقط تاریخ معتبر سال غالب را دارد. در صورت تفاوت تعداد واقعی، اعداد دادهٔ زیر را مبنا قرار دهید. قالب پاسخ: {"charts":{"shift":{"observation":"...","question":"...","action":"..."}},"conclusion":"..."}. داده: ${JSON.stringify(payload())}`}
function extractText(r,provider){if(provider==='gemini')return (r.candidates||[]).flatMap(x=>x.content?.parts||[]).map(x=>x.text||'').join('');return r.choices?.[0]?.message?.content||''}
function parse(text){let value=JSON.parse(text.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,''));if(!value||typeof value!=='object'||typeof value.charts!=='object'||typeof value.conclusion!=='string')throw Error('پاسخ باید JSON شامل charts و conclusion باشد.');const needed=state.charts.filter(c=>c.selected),charts={};for(const c of needed){const part=value.charts[c.id];if(!part||['observation','question','action'].some(k=>typeof part[k]!=='string'||!part[k].trim()))throw Error(`تحلیل نمودار «${c.title}» کامل نیست.`);charts[c.id]={observation:part.observation.slice(0,300),question:part.question.slice(0,250),action:part.action.slice(0,250),caveat:'این‌ها تعداد گزارش‌های ثبت شده‌اند؛ بدون مخرج مواجهه، از آن‌ها نرخ خطر یا علت قطعی نتیجه نمی‌شود.'}}return {charts,conclusion:value.conclusion.slice(0,1250)}}
function render(){const box=q('aiResults');if(!state.ai){box.innerHTML='';return}box.innerHTML='<h3>پیش‌نمایش تحلیل قابل ویرایش</h3>'+state.charts.filter(c=>c.selected&&state.ai.charts[c.id]).map(c=>`<article class="ai-result"><h4>${escapeHtml(c.title)}</h4>${[['observation','یافته'],['question','پرسش'],['action','اقدام']].map(([k,l])=>`<label>${l}<textarea data-ai-chart="${c.id}" data-ai-field="${k}">${escapeHtml(state.ai.charts[c.id][k])}</textarea></label>`).join('')}</article>`).join('')+`<article class="ai-result ai-conclusion"><h4>نتیجه‌گیری اسلاید آخر</h4><textarea id="aiConclusion">${escapeHtml(state.ai.conclusion)}</textarea></article>`}
function apply(text){state.ai=parse(text);render();q('aiStatus').textContent='تحلیل دریافت شد. متن‌ها را بازبینی و در صورت نیاز ویرایش کنید؛ خروجی پاورپوینت از همین متن استفاده می‌کند.'}
window.addEventListener('safety-data-loaded',()=>{q('aiRun').disabled=false;q('aiCopy').disabled=false;q('aiApply').disabled=false;q('aiStatus').textContent='آمار تجمیعی آمادهٔ تحلیل است. نمودارهای دلخواه را انتخاب کنید.';render()});
q('aiCopy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(prompt());q('aiStatus').textContent='پرامپت کپی شد. پاسخ JSON ابزار دیگر را در کادر همین صفحه وارد کنید.'}catch(e){q('aiStatus').textContent='کپی خودکار ممکن نشد. صفحه را از localhost یا HTTPS باز کنید.'}});
q('aiApply').addEventListener('click',()=>{try{apply(q('aiPaste').value)}catch(e){q('aiStatus').textContent='خطای پاسخ: '+e.message}});
q('aiProvider').addEventListener('change',()=>{const isGemini=q('aiProvider').value==='gemini';q('aiKey').value='';q('aiKey').placeholder=isGemini?'کلید رایگان Gemini API':'کلید OpenRouter API';q('aiKeyLink').href=isGemini?'https://aistudio.google.com/api-keys':'https://openrouter.ai/settings/keys';q('aiKeyLink').textContent=isGemini?'Google AI Studio':'OpenRouter';q('aiStatus').textContent='سرویس انتخاب شد. کلید همان سرویس را وارد کنید.'});
q('aiRun').addEventListener('click',async()=>{const key=q('aiKey').value.trim();if(!key){q('aiStatus').textContent='برای ارسال مستقیم، کلید رایگان سرویس انتخابی را وارد کنید؛ یا پرامپت را کپی کنید.';return}const provider=q('aiProvider').value,button=q('aiRun');button.disabled=true;q('aiStatus').textContent='در حال تحلیل آمار تجمیعی…';try{const url=provider==='gemini'?'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent':'https://openrouter.ai/api/v1/chat/completions';const headers=provider==='gemini'?{'Content-Type':'application/json','x-goog-api-key':key}:{'Content-Type':'application/json','Authorization':'Bearer '+key};const body=provider==='gemini'?{contents:[{parts:[{text:prompt()}]}],generationConfig:{responseMimeType:'application/json'}}:{model:'openrouter/free',messages:[{role:'user',content:prompt()}]};const response=await fetch(url,{method:'POST',headers,body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error?.message||`HTTP ${response.status}`);const reply=extractText(result,provider);if(!reply)throw Error('سرویس پاسخی برنگرداند.');apply(reply)}catch(e){q('aiStatus').textContent='تحلیل انجام نشد: '+e.message+' اگر سهمیه یا اتصال محدود است، از گزینهٔ کپی پرامپت استفاده کنید.'}finally{button.disabled=false}});
q('aiResults').addEventListener('input',e=>{if(e.target.id==='aiConclusion'&&state.ai)state.ai.conclusion=e.target.value;else if(e.target.dataset.aiChart&&state.ai?.charts[e.target.dataset.aiChart])state.ai.charts[e.target.dataset.aiChart][e.target.dataset.aiField]=e.target.value});
})();
