/* All parsing and reporting run locally in the browser. No row data is persisted. */
const $ = id => document.getElementById(id);
const months = ['فروردین','اردیبهشت','خرداد','تیر','مرداد','شهریور','مهر','آبان','آذر','دی','بهمن','اسفند'];
const fields = ['ردیف','نام بیمارستان','نام بخش گزارش دهنده','بخش 2','شیفت وقوع خطا','نوع گزارش خطا','تاریخ وقوع خطا','نوع خطا','علت وقوع خطا','سن بیمار','عنوان خطا','نوع خطا2','سمت','تاریخ ثبت فرم'];
const protectedFields = new Set(['نام و نام خانوادگی تکمیل کننده','شماره پرونده','شرح خطا','نام گزارش دهنده']);
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state = { rows:[], headers:[], charts:[], filename:'', period:'', errors:0 };
function clean(v){ return String(v ?? '').replace(/[\u200c\u200d]/g,' ').replace(/\s+/g,' ').trim(); }
function dateParts(v){ const m=clean(v).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).match(/(1[34]\d{2})\D*(0?[1-9]|1[0-2])\D*(\d{1,2})/); return m?{year:m[1],month:Number(m[2]),day:Number(m[3])}:null; }
function count(rows,field){ const m=new Map(); rows.forEach(r=>{const k=clean(r[field])||'ثبت نشده';m.set(k,(m.get(k)||0)+1)});return [...m].sort((a,b)=>b[1]-a[1]); }
function topCounts(rows,field,n=12){const a=count(rows,field);return a.length>n?[...a.slice(0,n),['سایر بخش‌ها',a.slice(n).reduce((s,x)=>s+x[1],0)]]:a}
function titleForPeriod(rows){let dates=rows.map(r=>dateParts(r['تاریخ وقوع خطا'])).filter(Boolean);let years=[...new Set(dates.map(d=>d.year))];let ms=[...new Set(dates.map(d=>d.month))].sort((a,b)=>a-b);return `${years.join('، ')||'نامشخص'} · ${ms.map(m=>months[m-1]).join('، ')||'ماه نامشخص'}`;}
async function parseWorkbook(buffer){const z=await JSZip.loadAsync(buffer);const wb=z.file('xl/workbook.xml');if(!wb)throw Error('فایل، قالب معتبر Excel نیست.');
 const xml=s=>new DOMParser().parseFromString(s,'application/xml');const shared=z.file('xl/sharedStrings.xml')?xml(await z.file('xl/sharedStrings.xml').async('string')):null;
 const strings=shared?[...shared.getElementsByTagName('si')].map(si=>[...si.getElementsByTagName('t')].map(t=>t.textContent).join('')):[];
 const sheet=z.file('xl/worksheets/sheet1.xml');if(!sheet)throw Error('برگهٔ داده در فایل پیدا نشد.');const doc=xml(await sheet.async('string'));if(doc.querySelector('parsererror'))throw Error('ساختار برگهٔ اکسل قابل خواندن نیست.');
 const matrix=[...doc.getElementsByTagName('row')].map(row=>{let cells=[];[...row.getElementsByTagName('c')].forEach(c=>{let ref=c.getAttribute('r')||'';let letters=ref.match(/^[A-Z]+/);if(!letters)return;let idx=[...letters[0]].reduce((a,v)=>a*26+v.charCodeAt(0)-64,0)-1;let v=c.getElementsByTagName('v')[0]?.textContent??'';if(c.getAttribute('t')==='s')v=strings[Number(v)]??'';if(c.getAttribute('t')==='inlineStr')v=[...c.getElementsByTagName('t')].map(x=>x.textContent).join('');cells[idx]=v;});return cells;});
 const headIdx=matrix.findIndex(r=>r.some(v=>clean(v)==='ردیف')&&r.some(v=>clean(v)==='تاریخ وقوع خطا'));if(headIdx<0)throw Error('ستون‌های ردیف و تاریخ وقوع خطا پیدا نشدند. قالب فایل را بررسی کنید.');
 const headers=matrix[headIdx].map(clean);const required=['نام بخش گزارش دهنده','بخش 2','شیفت وقوع خطا','نوع گزارش خطا','تاریخ وقوع خطا','نوع خطا','سن بیمار','عنوان خطا','نوع خطا2','سمت'];let missing=required.filter(h=>!headers.includes(h));if(missing.length)throw Error('ستون‌های مورد نیاز یافت نشد: '+missing.join('، '));
 let rows=[],invalid=0;matrix.slice(headIdx+1).forEach(values=>{if(!values.some(v=>clean(v)))return;const r={};headers.forEach((h,i)=>{if(h)r[h]=values[i]??''});if(!dateParts(r['تاریخ وقوع خطا'])){invalid++;return}rows.push(r)});if(!rows.length)throw Error('هیچ رکورد دارای تاریخ معتبر پیدا نشد.');return {headers,rows,invalid};}
function chartDefinitions(rows){let dated=rows.map(r=>dateParts(r['تاریخ وقوع خطا']));let keyed=new Map();dated.forEach(d=>{let key=`${d.year}/${String(d.month).padStart(2,'0')}`;keyed.set(key,(keyed.get(key)||0)+1)});let trend=[...keyed].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,n])=>[`${months[Number(k.slice(-2))-1]} ${k.slice(0,4)}`,n]);
 const shift=count(rows,'شیفت وقوع خطا'), occurrence=topCounts(rows,'بخش 2'), reporting=topCounts(rows,'نام بخش گزارش دهنده'), types=count(rows,'نوع خطا'), reportType=count(rows,'نوع گزارش خطا'), errors=topCounts(rows,'نوع خطا2'), roles=count(rows,'سمت'), causes=topCounts(rows,'علت وقوع خطا');
 const ageBins=['۰–۱۸','۱۹–۳۰','۳۱–۴۰','۴۱–۵۰','۵۱–۶۰','۶۱–۷۰','۷۱–۸۰','بالای ۸۰','نامشخص'];let ages=ageBins.map(x=>[x,0]);rows.forEach(r=>{const n=Number(r['سن بیمار']);let i=!clean(r['سن بیمار'])||!Number.isFinite(n)?8:n<=18?0:n<=30?1:n<=40?2:n<=50?3:n<=60?4:n<=70?5:n<=80?6:7;ages[i][1]++});
 const defs=[
 ['shift','فراوانی خطا به تفکیک شیفت','توزیع تعداد ثبت‌ها در شیفت‌های کاری',shift,'bar'],
 ['trend','روند خطاهای ثبت شده','تعداد گزارش در ماه‌های دوره',trend,'line'],
 ['occurrence','فراوانی بروز خطا در هر بخش','ستون «بخش 2» در خروجی سامانه',occurrence,'bar'],
 ['reporting','بخش‌های گزارش دهنده خطا','ستون «نام بخش گزارش دهنده»',reporting,'bar'],
 ['cross','بخش گزارش دهنده × شیفت','پنج واحد نخست به تفکیک شیفت',reporting.slice(0,5).map(([name])=>[name,...shift.slice(0,3).map(([s])=>rows.filter(r=>clean(r['نام بخش گزارش دهنده'])===name&&clean(r['شیفت وقوع خطا'])===s).length)]),'cross'],
 ['reportType','نوع گزارش خطا','خوداظهاری، گزارش سایرین و سایر موارد',reportType,'donut'],
 ['severity','توزیع نوع خطا','نزدیک به خطا، بدون آسیب و همراه با آسیب',types,'donut'],
 ['errorKind','انواع خطاهای ثبت شده','طبقه‌بندی «نوع خطا2»',errors,'bar'],
 ['causes','علت وقوع خطا','فراوانی علت‌های ثبت شده',causes,'bar'],
 ['roles','گزارش دهندگان بر اساس سمت','فراوانی نقش‌های شغلی',roles,'bar'],
 ['age','توزیع سنی بیماران','بر اساس تعداد رکوردهای دارای سن',ages,'bar'] ];
 return defs.map(([id,title,subtitle,data,type])=>({id,title,subtitle,data,type,selected:true,analysis:''}));}
function svgChart(chart){const data=chart.data;let max=Math.max(1,...data.map(d=>Math.max(...d.slice(1).map(Number))));let colors=['#119987','#4b8cda','#e5a858','#a684d8','#ec7773'];if(chart.type==='donut'){let sum=data.reduce((s,d)=>s+d[1],0)||1,cx=175,cy=118,r=75,start=0;let arcs=data.map(([k,v],i)=>{let len=v/sum*2*Math.PI,from=start;start+=len;let x1=cx+r*Math.cos(from),y1=cy+r*Math.sin(from),x2=cx+r*Math.cos(start),y2=cy+r*Math.sin(start),large=len>Math.PI?1:0;return len>=6.283?`<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="27"/>`:`<path d="M ${x1} ${y1} A ${r} ${r} 0 ${large} 1 ${x2} ${y2}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="27"/>`}).join('');let legend=data.slice(0,5).map(([k,v],i)=>`<text x="${340}" y="${45+i*37}" text-anchor="start" direction="rtl" style="font-size:11px">● ${escapeHtml(k.slice(0,25))} · ${v}</text>`).join('');return `<svg viewBox="0 0 640 240">${arcs}<circle cx="175" cy="118" r="52" fill="white"/><text x="175" y="114" text-anchor="middle" style="font-size:20px;font-weight:bold">${sum}</text><text x="175" y="134" text-anchor="middle">ثبت</text>${legend}</svg>`}
 if(chart.type==='cross'){let rowH=38;let items=data.map((d,i)=>{let y=35+i*rowH;let segments=d.slice(1).map((v,j)=>`<rect x="${190+j*125}" y="${y-15}" width="${Math.max(2,v/max*110)}" height="16" rx="4" fill="${colors[j]}"/><text x="${190+j*125+Math.max(2,v/max*110)+4}" y="${y-2}">${v}</text>`).join('');return `<text x="175" y="${y}" text-anchor="end">${escapeHtml(d[0].slice(0,22))}</text>${segments}`}).join('');return `<svg viewBox="0 0 640 240">${items}<text x="200" y="236">شیفت‌های غالب در هر بخش</text></svg>`}
 if(chart.type==='line'){let coords=data.map((d,i)=>[40+i*(560/Math.max(data.length-1,1)),205-d[1]/max*165]);let line=coords.map(([x,y])=>`${x},${y}`).join(' ');return `<svg viewBox="0 0 640 250"><line x1="30" y1="205" x2="620" y2="205" stroke="#dce8ea"/><polyline points="${line}" fill="none" stroke="#119987" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${coords.map(([x,y],i)=>`<circle cx="${x}" cy="${y}" r="5" fill="#119987"/><text x="${x}" y="${y-12}" text-anchor="middle">${data[i][1]}</text><text x="${x}" y="228" text-anchor="middle">${escapeHtml(data[i][0].slice(0,16))}</text>`).join('')}</svg>`}
 let n=data.length,rowH=Math.min(36,210/Math.max(n,1));return `<svg viewBox="0 0 640 245">${data.map(([k,v],i)=>{let y=12+i*rowH,w=v/max*280;return `<text x="278" y="${y+rowH*.68}" text-anchor="end">${escapeHtml(String(k).slice(0,37))}</text><rect x="290" y="${y+3}" width="${w}" height="${Math.max(8,rowH-8)}" rx="5" fill="${colors[i%colors.length]}"/><text x="${296+w}" y="${y+rowH*.68}">${v}</text>`}).join('')}</svg>`;}
function render(){let rows=state.rows;let topShift=count(rows,'شیفت وقوع خطا')[0], peak=state.charts.find(c=>c.id==='trend').data.slice().sort((a,b)=>b[1]-a[1])[0];$('period').textContent='دوره گزارش: '+state.period;
 $('kpis').innerHTML=[['◈',rows.length,'کل خطاهای ثبت شده'],['◷',peak?peak[1]:'—',`بیشترین ثبت ماهانه · ${peak?.[0]||'—'}`],['☀',topShift?.[1]??'—',`شیفت پرتکرار · ${topShift?.[0]||'—'}`],['✚',new Set(rows.map(r=>clean(r['بخش 2'])).filter(Boolean)).size,'بخش دارای ثبت خطا']].map(([icon,n,label])=>`<div class="kpi"><div class="icon">${icon}</div><strong>${n}</strong><small>${escapeHtml(label)}</small></div>`).join('');
 $('chartGrid').innerHTML=state.charts.map((c,i)=>`<article class="card"><div class="card-top"><div><span class="eyebrow">نمودار ${String(i+1).padStart(2,'0')}</span><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.subtitle)}</p></div><label class="pick"><input type="checkbox" data-chart="${c.id}" ${c.selected?'checked':''}> انتخاب</label></div><div class="chart">${svgChart(c)}</div><details><summary>متن تحلیل و پرامپت هوش مصنوعی</summary><textarea data-analysis="${c.id}" placeholder="متن تحلیل تأیید شده را اینجا قرار دهید؛ در اسلاید نمودار نمایش داده می‌شود.">${escapeHtml(c.analysis)}</textarea><button class="copy" data-prompt="${c.id}">کپی پرامپت این نمودار</button></details></article>`).join('');
 $('monthFilter').innerHTML='<option value="">همه ماه‌ها</option>'+[...new Set(rows.map(r=>dateParts(r['تاریخ وقوع خطا'])).filter(Boolean).map(d=>`${d.year}/${String(d.month).padStart(2,'0')}`))].sort().map(s=>`<option value="${s}">${months[Number(s.slice(-2))-1]} ${s.slice(0,4)}</option>`).join('');$('tableHead').innerHTML='<tr>'+fields.filter(f=>state.headers.includes(f)&&!protectedFields.has(f)).map(f=>`<th>${escapeHtml(f)}</th>`).join('')+'</tr>';renderTable();selected();}
function renderTable(){let search=clean($('search').value).toLowerCase(),month=$('monthFilter').value;let data=state.rows.filter(r=>(!month||clean(r['تاریخ وقوع خطا']).startsWith(month))&&(!search||fields.some(f=>!protectedFields.has(f)&&clean(r[f]).toLowerCase().includes(search))));$('tableBody').innerHTML=data.slice(0,500).map(r=>'<tr>'+fields.filter(f=>state.headers.includes(f)&&!protectedFields.has(f)).map(f=>`<td title="${escapeHtml(r[f])}">${escapeHtml(r[f])}</td>`).join('')+'</tr>').join('');$('tableCount').textContent=`${data.length} رکورد${data.length>500?' · ۵۰۰ ردیف نخست نمایش داده شده‌اند':''}`;}
function selected(){let n=state.charts.filter(c=>c.selected).length;$('selectedCount').textContent=`${n} نمودار انتخاب شده`;$('exportBtn').disabled=!n}
function promptFor(c){return `نقش: تحلیلگر ایمنی بیمار در بیمارستان. بر اساس آمار ثبت شده در «${state.period}»، متن تحلیلی کوتاه و دقیق برای نمودار «${c.title}» بنویس. داده‌ها: ${JSON.stringify(c.data)}. فقط الگوی مشاهده‌شده را توضیح بده؛ ۲ تا ۳ فرضیه قابل بررسی و ۲ اقدام عملی پیشنهاد کن. از داده‌ها درباره علت قطعی، خطر نسبی، عملکرد افراد یا بخش‌ها نتیجه‌گیری نکن. تعداد گزارش را با نرخ وقوع خطا اشتباه نگیر؛ مخرجی مانند تعداد بیماران یا روزهای بستری در دسترس نیست. اگر داده ناقص یا دسته «ثبت نشده» وجود دارد، ذکر کن. حداکثر ۱۲۰ کلمه، فارسی رسمی و بدون نام بیمار یا کارکنان.`;}
async function makePpt(){const pptx=new PptxGenJS();pptx.layout='LAYOUT_WIDE';pptx.author='واحد ایمنی بیمار';pptx.subject='گزارش آماری خطاهای ثبت شده';pptx.title='پایش ایمنی بیمار · '+state.period;pptx.lang='fa-IR';pptx.rtlMode=true;const C={navy:'102F3A',teal:'119987',pale:'ECF7F5',text:'173342',muted:'6B8390',white:'FFFFFF'};const base=()=>{let s=pptx.addSlide();s.background={color:'F5F9FA'};s.addShape(pptx.ShapeType.rect,{x:0,y:0,w:13.333,h:.13,line:{color:C.teal},fill:{color:C.teal}});s.addText('✚  بیمارستان قلب شهید چمران اصفهان',{x:8.1,y:.28,w:4.7,h:.4,fontFace:'Vazirmatn',fontSize:11,color:C.teal,align:'right',rtlMode:true,margin:0});s.addShape(pptx.ShapeType.line,{x:.7,y:7.02,w:11.9,h:0,line:{color:'DAE6E9',width:1}});s.addText('واحد ایمنی بیمار  ·  '+state.period,{x:6.7,y:7.08,w:5.9,h:.23,fontFace:'Vazirmatn',fontSize:8,color:C.muted,align:'right',margin:0,rtlMode:true});return s};
 let cover=base();cover.addShape(pptx.ShapeType.roundRect,{x:.75,y:1.25,w:11.85,h:5.2,rectRadius:.2,line:{color:'DCEAE9'},fill:{color:C.navy}});cover.addText('گزارش پایش خطاهای بیمارستان',{x:2.1,y:2.2,w:9.5,h:.8,fontFace:'Vazirmatn',fontSize:32,bold:true,color:C.white,align:'right',rtlMode:true,breakLine:false,margin:0});cover.addText('بر پایه داده‌های ثبت شده در سامانه خطا',{x:2.1,y:3.2,w:9.5,h:.5,fontFace:'Vazirmatn',fontSize:17,color:'B9DEDA',align:'right',rtlMode:true,margin:0});cover.addText('دوره گزارش: '+state.period,{x:2.1,y:4.1,w:9.5,h:.6,fontFace:'Vazirmatn',fontSize:16,color:C.white,align:'right',rtlMode:true,margin:0});
 let overview=base();overview.addText('روند کلی خطاها | نگاهی به آمار و توزیع',{x:1,y:.85,w:11.3,h:.6,fontFace:'Vazirmatn',fontSize:26,bold:true,color:C.navy,align:'right',rtlMode:true,margin:0});let countTotal=state.rows.length,shift=count(state.rows,'شیفت وقوع خطا'),peak=state.charts.find(c=>c.id==='trend').data.slice().sort((a,b)=>b[1]-a[1])[0];[[`${countTotal}`,'تعداد کل گزارش‌ها'],[`${peak?.[1]??0}`,'بیشترین ثبت ماهانه · '+(peak?.[0]||'')],[`${shift[0]?.[1]??0}`,'شیفت پرتکرار · '+(shift[0]?.[0]||'')]].forEach(([n,l],i)=>{let x=1+i*4.05;overview.addShape(pptx.ShapeType.roundRect,{x,y:2.25,w:3.7,h:2.3,rectRadius:.1,line:{color:'DDEAE9'},fill:{color:C.white}});overview.addText(n,{x:x+.2,y:2.55,w:3.3,h:.8,fontFace:'Vazirmatn',fontSize:34,bold:true,color:C.teal,align:'center',margin:0});overview.addText(l,{x:x+.15,y:3.55,w:3.4,h:.5,fontFace:'Vazirmatn',fontSize:12,color:C.text,align:'center',rtlMode:true,margin:0})});overview.addText('این مقادیر تعداد گزارش‌های ثبت شده‌اند و بدون تعداد مواجهه یا بیماران، نرخ وقوع خطا محسوب نمی‌شوند.',{x:1.2,y:5.4,w:10.8,h:.6,fontFace:'Vazirmatn',fontSize:12,color:C.muted,align:'right',rtlMode:true,margin:0});
 for(const c of state.charts.filter(x=>x.selected)){let s=base();s.addText(c.title,{x:.8,y:.73,w:11.7,h:.57,fontFace:'Vazirmatn',fontSize:23,bold:true,color:C.navy,align:'right',rtlMode:true,margin:0});s.addText(c.subtitle,{x:.8,y:1.32,w:11.7,h:.4,fontFace:'Vazirmatn',fontSize:11,color:C.muted,align:'right',rtlMode:true,margin:0});s.addShape(pptx.ShapeType.roundRect,{x:.75,y:1.9,w:11.85,h:4.45,rectRadius:.09,fill:{color:C.white},line:{color:'E1EBED'}});
 // Native Office charts stay editable. For the cross-tab, group totals remain an accurate fallback.
 let data=c.type==='cross'?c.data.map(d=>[d[0],d.slice(1).reduce((a,b)=>a+b,0)]):c.data;let labels=data.map(d=>String(d[0]).slice(0,56)),values=data.map(d=>Number(d[1])||0);let kind=c.type==='line'?pptx.ChartType.line:c.type==='donut'?pptx.ChartType.doughnut:pptx.ChartType.bar;
 s.addChart(kind,[{name:'تعداد',labels,values}],{x:1.13,y:2.23,w:11.1,h:c.analysis?3.05:3.8,catAxisLabelFontFace:'Vazirmatn',valAxisLabelFontFace:'Vazirmatn',showLegend:false,showTitle:false,showValue:c.type==='donut',showPercent:false,showCatName:false,chartColors:['119987','4B8CDA','E5A858','A684D8','EC7773'],showMarker:true,showLine:true,showBorder:false,showValue:true,showSerName:false,catAxisLabelFontSize:10,valAxisLabelFontSize:10,valGridLine:{color:'E9F0F1',width:1},valAxisMinVal:0,showShadow:false,barDir:'bar',showHoleSize:58,layout:{x:.1,y:.05,w:.84,h:.85}});
 if(c.analysis)s.addText(c.analysis,{x:1.1,y:5.45,w:11.1,h:.66,fontFace:'Vazirmatn',fontSize:10,color:C.text,align:'right',valign:'mid',rtlMode:true,margin:.04,breakLine:false});}
 try{await pptx.writeFile({fileName:`گزارش-ایمنی-بیمار-${state.period.replace(/[^\d\p{L}]+/gu,'-')}.pptx`})}catch(e){throw Error('ساخت پاورپوینت ناموفق بود: '+e.message)} }
$('file').addEventListener('change',async e=>{let f=e.target.files?.[0];if(!f)return;$('fileName').textContent=f.name;$('notice').className='notice';$('notice').textContent='در حال خواندن فایل اکسل…';await new Promise(requestAnimationFrame);try{if(typeof JSZip==='undefined')throw Error('ابزار خواندن اکسل بارگذاری نشده است. فایل standalone.html را باز کنید یا کل پوشهٔ پروژه را یکجا نگه دارید.');let result=await parseWorkbook(await f.arrayBuffer());state.rows=result.rows;state.headers=result.headers;state.errors=result.invalid;state.filename=f.name;state.period=titleForPeriod(result.rows);state.charts=chartDefinitions(result.rows);$('fileName').textContent=f.name;$('notice').className='notice';$('notice').textContent=`${result.rows.length} رکورد معتبر از «${f.name}» خوانده شد.${result.invalid?` ${result.invalid} سطر بدون تاریخ معتبر کنار گذاشته شد.`:''} داده‌ها فقط در این مرورگر پردازش می‌شوند.`;render()}catch(err){$('notice').className='notice error';$('notice').textContent='خطا در خواندن اکسل: '+(err?.message||String(err));console.error('Excel import failed',err)}});
$('search').addEventListener('input',()=>state.rows.length&&renderTable());$('monthFilter').addEventListener('change',()=>state.rows.length&&renderTable());$('chartGrid').addEventListener('change',e=>{let id=e.target.dataset.chart;if(id){state.charts.find(c=>c.id===id).selected=e.target.checked;selected()}});$('chartGrid').addEventListener('input',e=>{let id=e.target.dataset.analysis;if(id)state.charts.find(c=>c.id===id).analysis=e.target.value});$('chartGrid').addEventListener('click',async e=>{let id=e.target.dataset.prompt;if(!id)return;let c=state.charts.find(c=>c.id===id);await navigator.clipboard.writeText(promptFor(c));e.target.textContent='پرامپت کپی شد ✓';setTimeout(()=>e.target.textContent='کپی پرامپت این نمودار',2000)});$('exportBtn').addEventListener('click',async()=>{let b=$('exportBtn');b.disabled=true;b.textContent='در حال ساخت…';try{await makePpt();b.textContent='دریافت پاورپوینت ←'}catch(e){$('notice').className='notice error';$('notice').textContent=e.message;b.textContent='تلاش دوباره'}finally{selected()}});

window.addEventListener('error',e=>{if(!state.rows.length){$('notice').className='notice error';$('notice').textContent='اجرای برنامه متوقف شد: '+(e.message||'یکی از فایل‌های برنامه بارگذاری نشده است. از standalone.html استفاده کنید.')}});
